---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2: 
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
citation: apa.csl
---
  
# Experiment 2: Semantic predictability facilitates comprehension of degraded speech in a graded manner

In the previous chapter we have shown that when listeners attend to the context, they gain facilitatory effect of predictability while listening to a degraded speech.
However, there were a few lacunae in the study, which warrant further examination to bolster as well as extend this conclusion.
There was an implicit assumption that all the correct responses were borne out of correct identification of the context evoking words (i.e., the verbs).
We also did not consider if listeners adapted to the degraded speech and how such an adaptation could modulate contextual facilitation.
And most importantly, we only showed that there is a difference between high and low predictability sentences, the granularity of predictability could not be tested.
The aim of the study described in this chapter is to address these limitations and examine if listeners formed narrowed expectations or whether predictions are generated across a wide range of probable sentence endings in a graded manner.
Here, we consider the accuracy of context identification (not just the accuracy of target word identification) as well as the possible learning effect due to adaptation to degraded speech.
The results showed that in contrast to the *narrowed expectations* view postulated for *predictive processing in degraded speech comprehension*,
listeners probabilistically preactivate upcoming words from a wide range of semantic space, not limiting only to highly probable sentence endings.
We also did not find any learning effects --
We speculate that when there is a trial-by-trial variation in semantic feature (i.e., sentence predictability), listeners do not adapt to low-level perceptual property (i.e., speech quality).

## Introduction

In the literature of speech perception and sentence processing, studies have argued that prediction is either probabilistic and graded, or it is all-or-none.
Very few studies have investigated such theoretical questions within the domain of degraded speech comprehension [e.g. @Strauss2013; see also @Corps2020; @vanOs2021].
As we have elaborated in Chapter 2, @Strauss2013 postulated that listeners cannot preactivate less predictable sentence endings in an adverse listening condition:
They proposed that the facilitatory effect of predictability is limited to only highly predictable sentence endings at a moderate level of spectral degradation of speech.
Although the contextual facilitation is supported by the results of Obleser and colleagues,
their study was conducted before @Strauss2013, and were not designed to tell if prediction was graded.
<!-- Therefore, the expectancy searchlight model of @Strauss2013 is in line with all-or-none prediction account. -->
<!--Many studies have, nonetheless, shown that at a moderate level of degradation, listeners rely on context information and gain contextual facilitation [e.g., @Obleser2007; @Sheldon2008a; @Obleser2010; Davis...].
For example, @Obleser2010 compared listeners response accuracy at high and low predictability sentences at 1. 2. 4.... channels noise vocoding conditions.
They found that there was a significant difference between high and low predictability sentences when speech was degraded by noise vocoding through 2, 6, ... channels.-->
<!-- I can remove the description of why no predictability effects at less (and more) channels from previous chapter and include it here instead. -->
<!--They concluded that semantic predictability facilitates language comprehension at moderate levels of speech degradation.
However, they did not test for adaptation to degraded speech (which was a limitation due of the fMRI^[fMRI=functioanl Magnetic Resonance Imaging] design), nor did they take into account a correct identification of context.
One or both of these limitations apply to other studies that conclude facilitatory effect of predictability [@Obleser2007; @Sheldon2008a; @Sheldon2008b; see also, @Hunter2018; @Amicheti2018].-->

In this chapter, our main aim is to replicate the previous findings of facilitatory effect of predictability,
and extend them further by testing if listeners form *narrowed expectations* while listening to moderately degraded speech.
In line with @Strauss2013's argument, listeners' can form predictions that are restricted to only highly probable sentence endings.
On the opposite, listeners' can garnet expectations about an upcoming word based on how likely the word is to appear in the context,
and hence form a probabilistic prediction.
We also test the possible learning effect due to potential perceptual adaptation and its effect on contextual facilitation if at all.
We set a metric of measurement of language comprehension that considers whether or not listeners correctly identified the context information.

## Background

**Predictability effects in degraded speech perception**:
So far in this thesis, we have shown that predictability plays a facilitatory role in comprehension of degraded speech when listeners attend to the sentence context (Chapter 5).
In their studies, Obleser and colleagues [@Obleser2007; @Obleser2010; @Obleser2011], used sentences of two levels of semantic predictability (high and low) and systematically degraded the speech signal by passing it through various numbers of noise vocoding channels ranging from 1 to 32 in a series of behavioral and neuroimaging studies.
They observed contextual facilitation at moderate levels of speech degradation (at 4 channels, or 8 channels noise vocoding).
That is, participants relied on the sentence context when the speech signal was degraded but intelligible enough.
Accuracy of word recognition was found to be higher for highly predictable target words than for less predictable target words at such moderate levels of speech degradation [@Obleser2010].
Even at different cognitive load, @Hunter2018 observed a similar predictability effect.
However, the granularity and the nature of prediction remains yet to be tested.
None of the studies mentioned above were designed (or their data analyzed) to test if the the facilitatory effect of prediction is graded and probabilistic, or if it is narrowed and all-or-none.

**Adaptation to degraded speech**:
With a repeated exposure to degraded speech, listeners' comprehension improves over time [@Samuel2009; @Guediche2014] which we have comprehensively discussed in Chapter 2.
Studies like those of @Davis2005 and @Erb2013 have shown that when participants are presented with a single noise condition, i.e., a single level of spectral degradation of speech, their response accuracy increases over the course of experiment.
In these experiments, only one speech degradation level was presented in one block.
So there was no uncertainty about the next-trial speech degradation from the participants' perspective.
Importantly, there was no variation in predictability of target word.
Similarly, the experiments which varied target word predictability and demonstrated the presence of contextual facilitation [e.g., @Obleser2007; @Sheldon2008a; @Sheldon2008b; @Obleser2010; @Strauss2013; @Hunter2018],
did not test for adaptation to degraded speech. <!-- should there be an interplay between such adaptation and contextual facilitation.-->
But we cannot ignore the facts that listeners learning effect might be absent with a change in the characteristics of auditory signal throughout the experiments [@Mattys2012];
and comprehension is impaired by any such trial-by-trial variability in the characteristics of distorted speech [@Sommers1994; see also, @Dahan2006].

**Measurement of language comprehension**:
How we measure language comprehension has not been to be guided by specific theoretical motive to a large extent in the existing literature.
Studies that reported contextual facilitation in degraded speech comprehension have used proportion of correctly reported *final* words only [e.g., @Sheldon2008a].
Obleser??? measured language comprehension as accuracy of identification of sentence final word recognition.WHAT WAS THE EXACT MEASUREMENT??
Other studies like, @Erb2013 and @Hakonen2017 used *report scores* [@Peelle2013] that measure proportion of correctly recognized words per sentence.
Such discrepancy makes cross-study comparison difficult,
and more importantly, none of these measures take into account if listeners have correctly identified the context [cf. @Amichetti2018; and prediction hinders study cited in Winn's paper.].


Stemming from the results of Chapter 5, and from the motivation driven by the open questions outlined above, the goals of the study in this chapter were threefold:
The first goal was to replicate the previous findings of facilitatory effect of predictability, and test if listeners form *narrowed expectations*.
Obleser and colleagues showed predictability effects (or contextual facilitation) only at a moderate level of speech degradation by using just two levels of sentence predictability (high and low).
Our use of three levels of target-word predictability, in contrast to only two levels in Obleser and colleagues', will let us test the narrowed expectations view when we take into account the accuracy of context.
If the listeners form a narrowed prediction only for high-cloze target words, then the facilitatory effect of semantic prediction will be observed only at these highly predictable sentence endings.
Listeners’ response to medium-cloze target words and low-cloze target words would be expected to be quite similar as these two will fall out of the range of narrowed prediction.
However, if the listeners’ predictions are not restricted to highly predictable target words, then they form predictions across a wide range of semantic context proportional to the probability of occurrence of the target word. 
In addition to highly predictable sentence endings, listeners will also form predictions for less predictable sentence endings.
Such predictions, however, will depend on the probability of occurrence of the target words.
In other words, listeners form predictions also for less expected sentence endings;
and the semantic space of prediction depends on the probability of occurrence of those sentence endings.
The addition of sentences with medium-cloze target words in the present study thus allows us to differentiate whether listeners form all-or-none prediction restricted to high-cloze target words, or a probabilistic prediction for words across a wide range of cloze probability.

There is a variation in the sentences we use, i.e., they are high, medium and low predictability sentences, and they are degraded at different levels of spectral degradation.
So our second goal was to investigate the role of uncertainty about next-trial speech features on perceptual adaptation by varying the *global channel context* on the comprehension of degraded speech.
To study this, we presented sentences of different levels of predictability blocked by each channel conditions (predictable channel context), and pseudo-randomized across all channels (unpredictable channel context).
Based on previous findings, we expected that in the unpredictable channel context (i.e., when sentences are presented in a random order of spectral degradation) participants’ word recognition performance will be worse than in the predictable channel context [i.e., when the sentences are blocked by noise-vocoding; @Sommers1994; @Garrido2011; @Vaden2013].
To further examine perceptual adaptation, we also considered the effect of trial number in the analyses of data.
<!-- Since we are using degraded speech, and listeners can adapt to degraded speech in a short time, our third goal is to investigate if adaptation to degraded speech  -->
<!--
We thus speculated that if the noise vocoded speech varies from one trial to the next then the adaptation to noise in this scenario might be different from the earlier case in which the noise condition is constant throughout the experiment.
Perceptual adaptation, however, is not limited to trial-by-trial variability of stimulus property.
Listeners can adapt to auditory signal at different time courses and time scales [@Atienza2002; see also, @Whitmire2016].
In addition to differences in intrinsic trial-by-trial variability and resulting short timescale trial-by-trial adaptation in two channel contexts, the global differences in the presentation of vocoded speech can result in a difference in the general adaptation at a longer timescale between predictable and unpredictable channel contexts.

We have mentioned the caveat in the existing metric of measurement of language comprehension.
Taking this into account, our third goal is to establish a sensitive metric of measurement of language comprehension that considers whether or not listeners correctly identify the context in a sentence.


There is a limited number of studies that has looked at how next-trial noise-uncertainty and global context of speech property influence adaptation.
For example, words were presented at +3 dB SNR and +10 dB SNR in a word recognition task in a pseudorandom order [@Vaden2013].
The authors wanted to minimize the certainty about the noise conditions in the block.
The same group of authors [@Vaden2015a; @Vaden2015b; @Eckert2016] proposed that an adaptive control system (cingulo opercular circuit) might be involved to optimize task performance when listeners are uncertain about upcoming trial.
However, we cannot make a firm conclusion about perceptual adaptation *per se* from their studies as they do not report the change in performance over the course of experiment.
Similarly, Obleser and colleagues [@Obleser2007; @Obleser2011; @Hartwigsen2015] also presented listeners with noise vocoded sentences (ranging from 2 to 32 channels of noise vocoding) in a pseudo-randomized order but did not report presence or absence of perceptual adaptation to noise vocoded speech.
In the abovementioned studies, the authors did not compare participants' task performance in the blocked design against the presentation in a pseudorandomized block of different noise conditions to make an inference about general adaptation to degraded speech at a longer timescale.
To examine the influence of uncertainty about next trial speech features and the global context of speech features on perceptual adaptation, we therefore compared language comprehension with a trial-by-trial variation of sentence predictability and speech degradation either in blocks, in which the noise vocoded channels were blocked, or in a randomized order.-->

<!-- Ironically, enough attention has not been given to the metric by which language comprehension is measured.
Therefore, in this chapter, we take into account the role of sentence context while measuring language comprehension. -->

## Methods

### Participants

We recruited two groups of participants via Prolific Academic and assigned them to one of the two groups:
*unpredictable channel context* (n=48; $\bar{x}$  $\pm$ SD = 24.44 $\pm$ 3.5 years; age range = 18-31 years; 16 females) and *predictable channel context* (n=50; $\pm$ SD = 23.6 $\pm$ 3.2 years; age range = 18-30 years; 14 females).
All participants were native speakers of German residing in Germany.
Exclusion criteria for participating in this study were self-reported hearing disorder, speech-language disorder, or any neurological disorder.
All participants received monetary compensation for their participation.
The study was approved by Deutsche Gesellschaft für Sprachwissenschaft (DGfS) Ethics Committee, and the participants provided consent in accordance with the Declaration of Helsinki.

### Materials

We used the same stimuli described in Section X.X.X in Chapter X.X.
The stimuli were digital recordings of 360 German sentences spoken by a female native speaker of German in a normal rate of speech.
All sentences were in present tense consisting of pronoun, verb, determiner, and object (noun) in the Subject-Verb-Object form.
We used 120 nouns to create three categorizes of sentences -- high predictability sentences (HP sentencs), medium predictability sentences (MP sentences) and low predictability sentences (LP sentences) -- that differed in cloze probability of sentence final target words.
(See Appendix A for examples.)
Their mean cloze probabilities were 0.022 $\pm$ 0.027 ($\bar{x}$  $\pm$ SD; range = 0.00 - 0.09) for LP sentences, 0.274 $\pm$ 0.134 ($\bar{x}$  $\pm$ SD; range = 0.1 - 0.55) for MP sentences, and 0.752 $\pm$ 0.123 ($\bar{x}$  $\pm$ SD; range = 0.56 - 1.00) for HP sentences.
The distribution of cloze probability across LP, MP and HP sentences are shown in Figure X.X.

In the unpredictable channel context, each participant was presented with 120 unique sentences: 40 HP, 40 MP and 40 LP sentences. Channel condition was also balanced across each sentence type, i.e., in each of HP, MP, and LP sentences, ten sentences passed through each noise vocoding channels -- 1, 4, 6, and 8 -- were presented.
This resulted into 12 experimental lists.
The sentences in each list were pseudo-randomized, that is, not more than 3 sentences of same noise condition (i.e., same noise vocoding channel), or same predictability condition appeared consecutively.
This randomization confirmed the uncertainty of next-trial speech quality (or degradation) in the global context of the experiment.

The same set of stimuli and experimental lists were used in the predictable channel context.
Each participant was presented with 120 unique sentences blocked by channel conditions, i.e., blocked by noise vocoding channels.
There were four blocks of stimuli.
Thirty sentences were presented in each of the four blocks.
In the first block, all sentences were 8 channels noise vocoded, followed by blocks of 6 channels, 4 channels, and 1 channel noise vocoded speech consecutively [@Sheldon2008a].
Within each block, 10 HP, 10 MP and 10 LP sentences were presented.
All the sentences were pseudo-randomized so that not more than three sentences of the same predictability condition appeared consecutively in each block.
This ascertained there was a certainty of next-trial speech quality (within each block) and an uncertianty of next-trial sentence predictability across all four blocks.

### Procedure

Participants were asked to use headphones or earphones.
A prompt to adjust loudness was displayed at the beginning of the experiment: A noise vocoded sound not used in the main experiment was presented, and participants were asked to adjust the loudness at their level of comfort.
One spoken sentence was presented in each trial.
Eight practice trials were presented before presenting 120 experimental trials.
They were asked to enter what they had heard (i.e., to type in the entire sentence) *via* keyboard.
Guessing was encouraged.
<!-- At the end of each trial, they were asked to judge their confidence in their response on a scale of 1 to 4, 1 being ‘just guessing’ to 4 being ‘highly confident’. -->
The response was not timed.<!-- Time limit to respond was not imposed on the participants.-->
The experiment was about 40 minutes long.

## Analyses

In the sentences used in our experiment, verbs evoke predictability of the sentence-final noun.
Therefore, the effect of predictability (evoked by the verb) on language comprehension can be rightfully measured if we consider only those trials in which participants identify the verbs correctly.
Verb-correct trials were considered as the sentence in which participants realized the context independent of whether they correctly understood the sentence final target noun.
Morphological inflections and typos were considered as correct.
We first filtered out those trials in which verbs were not identified correctly, i.e., trials with incorrect verbs.
Therefore, we excluded 2469 out of 5760 trials in unpredictable channel context and 2374 out of 6000 trials in predictable channel context from the analyses.
The 1 channel noise vocoding condition was dropped from the analyses as there were no correct responses in any of the trials in this condition.

We preprocessed and analysed data in R-Studio (Version 3.6.1; R Core Team, 2019) following the procedure described in [Chapter 4.4.4]{#analysis-main}.
Response accuracy was analyzed with Generalized Linear Mixed Models (GLMMs) with lme4 [@Bates2015] and lmerTest [@Kuznetsova2017] packages.
Binary responses (correct/incorrect) for all participants in both groups (predictable channel context and unpredictable channel context) were fit with a [binomial logistic mixed-effects model]{#binomial-logistic-mixed-effects-model}[@Jaeger2006; @Jaeger2008].
Noise condition (categorical; 4, 6, and 8 channels noise vocoding), target word predictability (categorical; HP, MP, LP), global channel context (categorical; predictable channel context and unpredictable channel context), and the interaction of noise condition and target word predictability were included in the fixed effects.

We first fitted a model with maximal random effects structure that included random intercepts for each participant and item [@Barr2013].
Both, by-participant and by-item random slopes were included for noise condition, target word predictability and their interaction.
To find the optimal model for the data, non-significant higher-order interactions were excluded from the fixed-effects structure (and from the random-effects structure) in a stepwise manner.
Model selection was based on Akaike Information Criterion (AIC) [@Grueber2011; @Richards2011] unless otherwise stated.
Random effects not supported by the data that explained zero variance according to singular value decomposition were excluded to prevent overparameterization.
This gave a more parsimonious model [@Bates2015a].
Such a model was then extended separately with: i) item-related correlation parameters, ii) participant-related correlation parameter, and iii) both item- and participant-related correlation parameters.
The best fitting model among the parsimonious and extended models, based on AIC, was then selected as the optimal model for our data.

We applied treatment contrast for noise condition (8 channels as a baseline; factor levels: 8 channels, 4 channels, 6 channels) and sliding difference contrast for target word predictability (factor levels: MP, LP, HP) and channel context (factor levels: unpredictable, predictable).
The results from the optimal model are shown in Table X.X.X, and are reported below in the Results section.

## Results

In this experiment, we tested i) whether predictability facilitates language comprehension only at a moderate level of spectral degradation, and ii) whether adaptation to degraded speech influences language comprehension.
We observed that the mean response accuracy increased with an increase in number of noise vocoding channels from 4 to 6 to 8, and with an increase in target word predictability from low to medium to high (see Figure X.X).
This trend is consistent across both the channel contexts; Figure X.X and Figure Y.Y show this trend for predictable channel context (i.e., blocked design) and unpredictable channel context (i.e., randomized design) respectively.
Mean accuracies across all conditions are given in Table X and Y, and Figure X.X.

These observations are confirmed by the results of statistical analyses.
We found a significant main effect of channel condition indicating that the response accuracy was higher in the 8 channels than in the 4 channels ($\beta$ = -2.87, SE = 0.22, *z* (6917) = -13.1, *p* <.001) and 6 channels ($\beta$ = -0.66, SE = 0.19, *z* (6917) = -3.42, *p* < .001).
There was a significant main effect of target word predictability suggesting that response accuracy was lower at low predictability sentences than both high predictability sentences ($\beta$ = 2.18, SE = 0.3, *z* (6917) = 7.2, *p* < .001) and medium predictability sentences ($\beta$ = -0.52, SE = 0.27, *z* (6917) = -1.97, *p* = .049).
We also found a significant interaction between channel condition and target word predictability ($\beta$ = -0.71, SE = 0.29, *z* (6917) = -2.44, *p* = .015).

We performed a subsequent subgroup analyses on each noise channel condition.
<!-- The same procedure as described above was followed. -->
They revealed that the interaction was driven by the effect of predictability at 4 channels:
The accuracy at high predictability sentences was higher than medium predictability sentences ($\beta$ = 1.14, SE = 0.37, *z* (1608) = 3.1, p < .001),
which in turn was also higher than low predictability sentences ($\beta$ = 1, SE = 0.24, *z* (1608) = 4.2, p < .001).
There was no significant difference in response accuracy between low predictability and high predictability sentences at both 6 channels ($\beta$ = 0.33, SE = 0.32, *z* (2590) = 1.04, *p* = .3) and 8 channels ($\beta$ = -0.014, SE = 0. 32, *z* (2719) = -0.04, *p* = .97).
However, response accuracy was higher in high predictability than in medium predictability sentences at both 6 channels ($\beta$ = 1.83, SE = 0.65, *z* (2590) = 2.83, p < .005) and 8 channels ($\beta$ = 1.54, SE = 0.61, *z* (2719) = 2.54, *p* = .011).

We also found a significant main effect of global channel context which showed that the response accuracy was higher in predictable channel context than in unpredictable channel context ($\beta$ = -0.27, SE = 0.14, *z* (6917) = -2.02, *p* = .04).

Further, to test the effect of practice on adaptation to degraded speech, we added trial number as a fixed effect in the maximal model.
Note that there were 30 trials in each block in the predictable channel context (i.e., blocked design).
For comparability, we divided unpredictable channel context (i.e., randomized design) into four blocks.
Then following the same procedure as above, we obtained an optimal model.
We did not find a significant main effect of trial number indicating that the response accuracy did not change throughout the experiment ($\beta$ = -0.0004, SE = 0.01, *z* (6917) = -0.05, *p* = 0.97).
It remained constant within each block in the predictable channel context ($\beta$ = -0.02, SE = 0.01, *z* (3291) = -1.43, *p* = 0.15) as well as in the unpredictable channel context ($\beta$ = 0.01 SE = 0.01, *z* (3291) = 1.05, *p* = 0.29).

## Discussion

The present study had three goals: i) to examine if previously reported facilitatory effect of semantic predictability  is restricted to only highly predictable sentence endings;
ii) to assess the role of perceptual adaptation on the facilitation of language comprehension by sentence predictability; and
iii) to use and establish a sensitive metric to measure language comprehension that takes into account whether listeners benefited from the semantic context of the sentence they have listened to.

Results of our study showed the expected interaction between predictability and degraded speech, that is, language comprehension was better for high-cloze than for low-cloze target words when the speech signal was moderately degraded by noise-vocoding through 4 channels, while the effect of predictability was absent when speech was not intelligible (noise-vocoding through 1 channel).
These results are fully in line with @Obleser2010;
we partly included identical sentences from their study in the present study (see Appendix A).
Importantly, in contrast to their study, we had also created sentences with medium-cloze target words (which were intermediate between high-cloze and low-cloze target words) and found that the effect of predictability was also significant when comparing sentences with medium-cloze target words against sentences with low-cloze target words at 4 channels noise-vocoding condition.
Recognition of a target word was dependent on its level of predictability (measured by cloze probability), and correct recognition was not just limited to high-cloze target words.
These significant differences in response accuracy between medium-cloze and low-cloze target words, and between medium-cloze and high-cloze target words at noise-vocoding through 4 channels show that the sentence-final word recognition is facilitated by semantic predictability in a graded manner.
This is in line with the findings from the ERP literature where it has been observed that semantic predictability, in terms of cloze probability of target word of a sentence, modulates semantic processing, indexed by N400, in a graded manner [@Delong2005; @Wlotko2012; @Nieuwland2018].

The interpretation of the observed graded effect of semantic predictability at the moderate level of spectral degradation (i.e., at noise-vocoding through 4 channels) provides a novel insight into how listeners form prediction when the bottom-up input is compromised.
That is, in an adverse listening condition, listeners rely more on top-down semantic prediction than on bottom-up acoustic-phonetic cues.
However, such a reliance on top-down prediction is not an all-or-none phenomenon; instead, listeners form a probabilistic prediction of the target word.
The effect of target word predictability on comprehension is not sharply focused solely on high-cloze target words like a ‘searchlight’.
But rather it is spread across a wide range including low-cloze and medium-cloze target words. As the cloze probability of the target words decreases from high to low, the focus of the searchlight becomes less precise.

<!-- ## Conclusion -->

In conclusion, this study provides novel insights into predictive language processing when bottom-up signal quality is compromised and uncertain:
We show that while processing moderately degraded speech, listeners form top-down predictions across a wide range of semantic space that is not restricted within highly predictable sentence endings.
In contrast to the narrowed expectation view, comprehension of words ranging from low- to high-cloze probability, including medium-cloze probability, is facilitated in a graded manner while listening to a moderately degraded speech.
We also found better speech comprehension when individuals were likely to have adapted to the noise condition in the blocked design compared to the randomized design.
We did not find learning effects at the trial-to-trial level of perceptual adaption – it may be that the adaptation was hampered by variation in higher-level semantic features (i.e., target word predictability).
We also argue that for the examination of semantic predictability effects during language comprehension, the analyses of response accuracy should be based on the trials in which context evoking words are correctly identified in the first place to make sure that listeners make use of the contextual cues instead of analyzing general word recognition scores.