---
#########################################
# options for knitting a single chapter #
#########################################
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
citation: apa.csl
---

# Experiment 3: Comprehension of degraded speech is modulated by the rate of speech

## Introduction

Language comprehension depends on the features and quality of speech signal
which is hampered in adverse listening conditions when speech is distorted, for example, due to change in rate of speech, and spectral degradation of speech.
Studies have shown that individuals can benefit from sentence context to compensate for distorted speech, at least when the level of speech degradation is at an intermediate level [e.g., @Obleser2010; @Bhandari2021], and at varying speech rate [@Aydelott2004; cf. @Goy2013].
The goal of the present study is to examine if sentence context can provide benefit when speech that is degraded at an intermediate level is presented at different rates (from slow, normal, and fast); speech in day-to-day conversation is distorted and presents itself at varying rate [e.g., @Krause2004].
In the following, we first summarize the impact of speech degradation in language comprehension, and its interaction with sentence context, and then the influence of speech rate on language comprehension, and its interaction with sentence context.

### Comprehension of degraded speech 

There are a number of studies showing that speech intelligibility and language comprehension is hampered when the bottom-up input is less intelligible due to spectral degradation of the speech signal [@Shannon1995; @Davis2005].
These studies have used noise vocoding as a methods of speech degradation. Here the speech signal is first divided into a specific number of frequency bands that corresponds to the number of vocoder channels.
The amplitude envelope within each frequency band is extracted, and the spectral information within it is replaced by noise.
The resulting vocoded speech contains temporal cues of the original speech, but it is difficult to understand – the lesser the number of vocoder channels, the lesser is the intelligibility.
More attentional resources are required to process and comprehend such degraded speech as compared to clean speech [e.g., @Wild2012; @Eckert2016].

Listeners rely more on top-down predictions when the speech signal is less intelligible due to spectral degradation.
Hence, they use the context information of the sentence to narrow down their predictions to a smaller set of semantic categories or words [@Strauss2013; see also, @Corps2020].
However, it is important that the context itself is ‘intelligible enough’ which is the case when the speech is only moderately degraded.
For example, Obleser and colleagues [@Obleser2007; @Obleser2010; @Obleser2011] found that at moderate levels of speech degradation, target words (the sentence final words) were better recognized when it was predictable from the sentence context than when it was unpredictable.
When the speech signal is clear or only very mildly degraded, there is typically no effect of predictability on comprehension, as even unpredictable words can be understood well in this condition (intelligibility is at ceiling).
In contrast, when the speech signal is extremely degraded (for instance at 1 channel noise vocoding), no facilitation from the context can be observed as the context itself cannot be understood and hence it cannot help with comprehension [@Obleser2010; @Bhandari2021].

Taken together, these studies show that semantic predictability facilitates comprehension of degraded speech at a moderate level of spectral degradation,
for example, at 4 channels noise vocoding,
when the speech is intelligible enough for the listeners to understand and form meaning representation of the context to generate predictions about upcoming word in a sentence.

### Comprehension of fast and slow speech

A change in speech rate manipulates the speech signal without producing any spectral degradation [@Charpentier1986; @Moulines1990; @Schlueter2014].
Understanding fast speech is more effortful compared to normal and slow speech, [e.g., @Mueller2019; @Winn2021b; see also, @Simantiraki2020], and its intelligibility and comprehension are reducec [@Fairbanks1957; @Peelle2005; @Schlueter2014].
The comprehension deficit in fast speech has been linked to speed of processing [@Gordonsalant1995; @Tun1998; see also, @Roennberg2013] given the limited time available to decode and understand the information in the fast speech.
It has also been suggested that the decoding and identification of incoming information in the fast speech puts a high demand on available cognitive resources [e.g., @Rodero2016] such that processing rapidly flowing information exhausts the cognitive resource required for language processing [@Gordonsalant2004; @Janse2009].
Hence, intelligibility and comprehension of fast speech is reduced compared to normal speech.
In contrast, the central auditory-language comprehension system is shown to be flexible to process slow speech without reducing intelligibility [@Lerner2014a; see also, @Vagharchakian2012].
However, some earlier studies have casted doubt on the processing advantage of slow speech [e.g., @Nejime1998; @Kemper1999; see also, @Liu2006; @Love2009].
In sum, compression and expansion of speech have differential effects on speech intelligibility and language comprehension.
Intelligibility and comprehension of fast speech is reduced while that of slow speech is generally increased compared to normal speech.

There are also a few studies so far that examined the role of predictability for understanding language when speech is fast or slow.
For instance, @Aydelott2004 used a priming paradigm to examine the effects of contextual cues, which were target words embedded in sentences, and compared fast speech to normal speech.
Target words were either congruent to the sentence context (100% cloze probability, i.e., in a constraining sentence context), incongruent (0% cloze probability, i.e., in an implausible sentence), or neutral (cloze probability not mentioned).  Results indicated no reduction in facilitatory effect of contextual cues (congruent versus neutral target words) at fast speech compared to normal speech.
In contrast, they found a reduced inhibitory effect (incongruent versus neutral target words). 
They argued that the constrained sentence context was easy to process – fast speech did not interfere   with the earlier stage of activation of words that matched the context (i.e., in congruent trials).
In contrast, the inhibition effect was reduced because there was less time to build up the representation of words in implausible sentence contexts so that less inhibition of the incongruent target word was needed.
However, in a replication study of @Aydelott2004, @Goy2013 found that the facilitatory effect was reduced in fast speech compared to normal speech.
They argued that the fast speech slowed down the activation of potential target words that matched the context, which effectively reduced the contextual facilitation.
In a recent study, @Winn2021b did not observe an increase in contextual facilitation for slow speech compared to normal speech, although the intelligibility was higher for slow speech.
In another experiment, @Koch2016a presented participants with a question-answer sequence of varying length across a wide range of normal and fast speech from Spoken Dutch Corpus [@Oostdijk2000].
They did not find any effect of predictability on word recognition. However, target word predictability and target word position in the sentences were not systematically controlled for in their study.

The effects of predictability at varying rates of presentation have been also investigated with self-paced reading studies.
For example, @Wlotko2015 presented participants with context evoking sentences followed by sentences containing a target word that was either expected (mean cloze probability of 74%) or unexpected (either same or different semantic category, both with cloze probability of approximately 0%).
They found that the facilitation effect (as reflected in the N400 amplitude) was reduced at the sentences that were presented fast compared to the ones that were presented slow.
They suggested that at fast rate of presentation, predictive preactivation of words was not common: There was not enough time to activate proper representation for processing of upcoming word.
In the same study, however, when the fast presentation was followed by slow presentation in separate blocks, semantic facilitation effect was not reduced.
That is, increase in the flow of information did not always impair the ability to predict   [see also, @Cole2020].
They argued that once the brain is engaged in predictive comprehension mode, for example, first in the slow presentation rate, it can then continue to allocate resources in the same mode under faster presentation rate.

In sum, there is already some evidence from studies applying various paradigms that the predictability of the sentence context interacts with the speech rate [@Sharit2003; @Aydelott2004; @Wlotko2015; @Winn2021b].
Benefits of using context information is not only limited under varying speech rates, but also when it is degraded [@Sheldon2008a; @Sheldon2008b; @Obleser2010; @Bhandari2021].
In the present study we will examine whether context information is still useful when the speech rate is fast (or slow) and degraded at the same time.

### Comprehension of degraded speech at varying rates of presentation

Real world listening is often a combination of more than one form of degradation and distortion of speech [@Gordonsalant1995; see also, @Cooke2014].
For example, speakers’ speech rate is variable, and there is a concurrent distortion due to background noise, reverberation, loss of spectral details in transmission, etc.
Some of the earliest studies examined the ‘devastating’ effects of ‘combinations of speech wave distortions’, but the combination of multiple distortions was not controlled for [@Martin1956; @Harris1960].
@Gordonsalant1995 systematically tested the effect of multiple, combined speech distortions.
They found that when fast speech was presented in a background noise, or with a reverberation then the word recognition accuracy in these combined distortions was lower than when the speech was presented in any single distortion condition.
@Adams2009 and @Adams2012 also showed that the addition of background noise had a detrimental effect on fast speech comprehension.
With an increase in speech rate, listeners required higher signal-to-noise ratio (SNR) to achieve 50% word recognition accuracy across a wide range of speech rate (90 to 250 words per minute, in a step of 9 words per minute) and background noise (+15 dB SNR, +5 dB SNR, and 0 dB SNR).
These studies showed that a combination of multiple distortions is worse than a single distortion.
It is noteworthy that neither of the distortions mentioned above (e.g., reverberation, background noise) interfere with fine structure of a speech signal which spectral degradation does.

So far, the evidence for the detrimental effects of combination of spectral degradation and speech compression is sparse. Most of the evidence on this comes from cochlear implant users [e.g., @Li2011; @Su2016] as they are the group of listeners whose auditory input is spectrally degraded.
@Iwasaki2002 found that a change in speech rate from slow to fast reduced word recognition accuracy in cochlear implantees.
Similarly, their speech perception was impaired with increased rate of speech, and it was improved when the speech rate was decreased [e.g., @Dincer2018].
@Meng2019 used both clean speech and spectrally degraded speech from MSP (Mandarin speech perception) and MHINT (Mandarin hearing in noise test) corpora in normal-hearing listeners and cochlear implant users.
They found that an increase in speech rate had much severe effect at spectrally degraded speech (4 channels sine-wave vocoded) than at clean speech.
To achieve the same level of accuracy, listeners required degraded speech to be much slower than the normal speech.
All of these studies indicated that when speech rate is increased, intelligibility and comprehension of degraded speech is reduced.
However, these studies did not examine the utility of context information when speech is distorted by more than one means, although the role of context and predictability in any one of these multiple distortions has been extensively discussed in the literature
[@Aydelott2004; @Sheldon2008a; @Sheldon2008b; @Obleser2010; @Goy2013; @Corps2020; @Bhandari2021; @Clark2021; @vanOs2021].

Taken together, the utility of semantic predictability in comprehension of degraded speech is fairly established whereas its effects in comprehension of both fast speech as well as slow speech is inconsistent.
Whether semantic predictability is beneficial even for degraded speech presented at different rates (fast and slow) has not been investigated yet.

### Study aims

We systematically examined if contextual facilitation at a moderate level of degradation varies with a change in speech rate.
The aim was to investigate if the increase (or decrease) in speech rate decreases (or increases) the facilitatory effect of semantic predictability that has been observed for moderately degraded speech at a normal speech rate.
Semantic predictability was manipulated by varying the cloze probability of target words, and moderate degradation was achieved by noise vocoding of speech through 4 channels;
@Obleser2010 and @Bhandari2021 have reported 4 channels noise vocoding to be the moderate degradation level at which contextual facilitation is observed.
Speech rate was manipulated by compression (or expansion) of the moderately degraded speech, by uniform pitch synchronous overlap-add technique that acts upon the temporal envelope of the speech signal, to make it fast (or slow).

To achieve the goal, we conducted two experiments in which listeners were required to listen to the sentences and type in the entire sentence they hear.
Sentence comprehension (word recognition accuracy) for high and low predictability sentences were assessed in fast speech (Experiment 1), and slow speech (Experiment 2).
Because the processing demand increases, and a limited time is to be available to process the context and form predictions [e.g., @Aydelott2004; @Wlotko2015], we expected that the contextual facilitation (i.e., the difference between high and low predictability sentences) will be reduced for fast speech compared to normal speech (Experiment 3A).
However, for slow speech due to abundance of time to process the degraded speech and the context, and reduction in effortful processing [e.g., @Winn2021b], we expected contextual facilitation to be increased compared to normal speech (Experiment 3B).
We expected that both increase and decrease in contextual facilitation will be primarily driven by the ease of processing high predictability sentences as compared to low predictability sentences [@Aydelott2004; @Goy2013].

## Experiment 3A

## Methods

### Participants

We recruited one group of participant (n=101; $\bar{x}$  $\pm$ SD = 23.14 $\pm$ XX years; age range = 18-31 years; 66 females, 1 preferred not to say) online via Prolific Academic.
All participants were native speakers of German residing in Germany.
Exclusion criteria for participating in this study were self-reported hearing disorder, speech-language disorder, or any neurological disorder.
All participants received monetary compensation for their participation.
The German Society for Language Science ethics committee approved the study and participants provided an informed consent in accordance with the declaration of Helsinki.

### Materials

We used the stimuli created by the method described in Section X.X.X in Chapter X.X which consisted of 360 German sentences spoken by a female native German speaker in an unaccented normal rate of speech.
Two categories of sentences that differed in the cloze probability of the target words (nouns) appearing the final word of the sentence were created from 120 nouns.
Thus, we compared high and low predictability sentences (abbreviated as HP and LP henceforth) which were sentences with low and high cloze target words respectively.
This gave 240 sentences that consisted of pronoun, verb, determiner, and object (noun).
The mean cloze probabilities of target words for low and high predictability sentences were 0.022 $\pm$ 0.027 ($\bar{x}$  $\pm$ SD; range = 0.00 - 0.09) and 0.752 $\pm$ 0.123 ($\bar{x}$  $\pm$ SD; range = 0.56 - 1.00) respectively.

These 240 sentences were passed compressed by a factor of 0.65 using PSOLA built-in in Praat to create fast and slow speech respectively.
Speech degradation of all normal, slow and fast speech was achieved by noise vocoding through 4 channels.

Each participant was presented with 120 unique sentences: 60 HP and 60 LP sentences.
Speech rate was also balanced across each predictability level.
The participants received 30 sentences with normal speed and 30 with fast speed in each of the predictability conditions resulting into 4 experimental lists.
The sentences in each list were pseudo-randomized, that is, not more than 3 sentences of same speed, or same predictability condition appeared consecutively.

### Procedure

Participants were asked to use headphones or earphones.
A sample of noise vocoded speech not used in the practice trial and the main experiment was provided so that the participants could adjust the loudness to a preferred level of comfort at the beginning of the experiment.
The participants were instructed to listen to the sentences and to type in the entire sentence by using the keyboard.
The time for typing in the response was not limited.
They were also informed at the beginning of the experiment that some of the sentences would be ‘noisy’ and not easy to understand, and in these cases, they were encouraged to guess what they might have heard.
They were not informed about the speed of speech being slow/fast or normal.
Eight practice trials with different levels of speech degradation were given to familiarize the participants with the task before presenting all 120 experimental trials with an inter-trial interval of 1000 ms.

## Analyses

We have already conceded in the previous chapter X.X.X that "the effect of predictability (evoked by the verb) on language comprehension can be rightfully measured if we consider only those trials in which participants identify the verbs correctly."
Therefore, we discarded the trials in which verbs were identified incorrectly -- XXXX out of XXXX trials.

We preprocessed and analysed data in R-Studio (Version 4.1.1; R Core Team, 2021) following the procedure described in [Chapter 4.4.4]{#analysis-main}.

Response accuracy was analyzed with Generalized Linear Mixed Models (GLMMs) with lme4 [@Bates2015] and lmerTest [@Kuznetsova2017] packages.
Binary responses (correct/incorrect) for all participants were fit with a [binomial logistic mixed-effects model]{#binomial-logistic-mixed-effects-model}[@Jaeger2006; @Jaeger2008].
Target word predictability (categorical; low and high), speech rate, or speed (categorical; xxx and xxx), and the interaction of predictability and speed were included in the fixed effects.

We fitted a model with maximal random effects structure that included random intercepts for each participant and item [@Barr2013].
Both, by-participant and by-item random slopes were included for target word predictability, speed and their interaction.

We applied treatment contrast for target word predictability (low predictability as a baseline; factor levels: low predictability, high predictability) and speed (normal speed as a baseline; factor levels: normal speed, fast speed).
The results from the maximal model are shown in Table X.X.X, and are reported below in the Results section.

## Results and Discussion

Mean response accuracies across all conditions are presented in Table 2.
We found a significant main effect of target word predictability ($\beta$ = 2.42, SE = .28, *z* = 8.55, *p* < .001) and a significant main effect of speech rate ($\beta$ = -0.98, SE = .24, *z* = 4.16, *p* < .001).
These suggested that participants’ response accuracy was higher for the high predictability sentences than for the low predictability sentences, and for normal speech than for fast speech.
We also found a significant interaction between target word predictability and speech rate ($\beta$ = 1.06, SE = .42, *z* = 2.50, *p* = .01). As it can be seen in Figure 1, the effect of target word predictability was reduced at fast speech. These results are shown in Table 3.

Separate planned analyses of each predictability level were performed following the same procedure described above in the Analysis section.
The results shown in Table 4 and Table 5 revealed that there was no significant main effect of speech rate at high predictability condition ($\beta$ = .02, SE = .34, *z* = .05, *p* = .96).
At low predictability condition, in contrast, we found a significant main effect of speech rate ($\beta$ = -.99, SE = .27, *z* = -3.72, *p* < .001).
Hence, response accuracy decreased at fast speech only for the low predictability condition. 

Separate planned analyses of each speech rate shown in Table 6 and Table 7 revealed that there was significant main effect of predictability in both normal speech ($\beta$ = 1.98, SE = 0.28, *z* = 7.05, *p* < .001) and fast speech conditions ($\beta$ = 2.67, SE = .37, *z* = 7.14, *p* < .001),
but the effect appeared to be higher for fast speech ($\beta$ = 2.67) than for normal speech ($\beta$ = 1.98).
This, however, is a result of significant reduction in accuracy at low predictability condition at fast speech rather than due to an increase in accuracy at high predictability condition. This can also be seen in Table 2 and Figure 1.

These results indicated an increase in response accuracy with an increase in target word predictability only at a normal speech rate.
Fast speech rate significantly affected accuracy at low predictability condition such that the contextual facilitation was essentially reduced.
These findings align with previous studies conducted with clean speech that found fast speech to reduce contextual facilitation [e.g., @Aydelott2004].
The results of the first experiment showed ease of processing high predictability sentences compared to low predictability sentences at moderately degraded fast speech.
We conducted another experiment to examine if slowing down the speech rate eases processing of both low and high predictability sentences and increases the contextual facilitation in comprehension of moderately degraded speech.

## Experiment 3B

## Methods

### Participants and Materials

We recruited 101 participants ($\bar{x}$ $\pm$ SD = 23.49 $\pm$ 3.26 years; age range = 18-30 years; 60 females, 1 preferred not to say) online via Prolific Academic.
Same procedure as Experiment 3A was followed.

We used the same sentences that were used in Experiment 1. However, the auditory recordings were expanded by a factor of 1.35 to create slow speech. All other procedure to create stimuli were identical to Experiment 1 resulting in two sets (one set of normal and one set of slow speech) of 240 sentences (120 high and 120 low predictability sentences) which were passed through 4 channels noise vocoding.

We followed the same steps as Experiment 3A to balance speech rate and predictability conditions and to pseudo-randomize these experimental conditions across all 4 lists.

### Procedure

Same procedure as Experiment 3A was followed.
We asked participants to report the entire sentence typing in what they heard.
And guessing was encouraged.

## Analyses

We followed the same data analyses procedure as in Experiment 3A.
Only the trials with verb-correct responses were considered in the analyses of accuracy of sentence-final target-words (i.e., nouns); 5495 out of 12120 trials were removed before the final analyses.

Target word predictability (categorical; low and high), speech rate, or speed (categorical; normal and slow), and the interaction of predictability and speed were included in the fixed effects.
Treatment contrast was applied to both target word predictability (low predictability as a baseline; factor levels: low predictability, high predictability) and speed (normal speed as a baseline; factor levels: normal speed, slow speed).
The results from the maximal model are shown in Table X.X.X, and are reported below in the Results section.

## Results and Discussion

Mean response accuracies for all experimental conditions are shown in Table 8.
There was a significant main effect of target word predictability indicating that participants’ response accuracy was higher for the high predictability condition than for the low predictability condition ($\beta$ = 2.58, SE = .30, *z* = 8.65, *p* < .001).
In contrast to Experiment 1, we did not find a significant main effect of speech rate ($\beta$ = -.08, SE = .15, *z* = .57, *p* = .568), nor there was a significant interaction between speech rate and target word predictability ($\beta$ = .44, SE = .27, *z* = 1.65, *p* = .099).
These suggested that there was no change in participants’ response accuracy with a reduction in speech rate, nor did the contextual facilitation significantly increase or decrease with slowing down of the speech rate.
It can be seen in Figure 2 that the effect of target word predictability did not change with speech rate.
These results are shown in Table 9.

We conducted separate planned analyses of each predictability level; the procedure was identical to the analyses in Experiment 1.
The results presented in Table 10 and Table 11 confirmed the findings of the main analysis reported above – there was no significant main effect of speech rate at both high predictability condition ($\beta$ = .39, SE = .22, *z* = 1.79, *p* = .073), as well as at low predictability condition ($\beta$ = -.11, SE = .16, *z* = -.71, *p* = .48).
Hence, as opposed to the findings of Experiment 1, response accuracy was not affected by change in speech rate at both high and low predictability sentences.

As in Experiment 1, we conducted separate planned analyses of each speech rate.
The results as shown in Table 12 and Table 13 revealed that there was a significant main effect of target word predictability at both slow speech rate ($\beta$ = 2.55, SE = .31, *z* = 8.14, *p* < .001) and normal speech rate ($\beta$ = 2.08, SE = .27, *z* = 7.68, *p* < .001);
the effect appeared to be higher for slow speech ($\beta$ = 2.55) than for normal speech ($\beta$ = 2.08).
This, however, was a result of smaller accuracy at low predictability condition at slow speech rather than due to a higher accuracy at high predictability condition. This can also be seen in Table 8 and Figure 2.

In contrast to Experiment 1, the findings of Experiment 2 did not indicate differential effect of speech rates in the comprehension of high and low predictability sentences.
While the results of Experiment 1 showed that speeding up the speech rate significantly reduced the accuracy of low predictability sentences, such a reduction was not observed in Experiment 2 when the speech rate was slowed down.
Although listeners’ response accuracy was reduced at both fast and slow speech rates as compared to normal speech rate, their ability to utilize context information was only impaired by fast speech. 

## General Discussion

The main goals of the present study were to examine if semantic predictability facilitates comprehension of moderately degraded speech at different speech rates given that the ease of processing the sentences varies with their predictability and speed.
The results of the two experiments revealed that fast speech selectively impedes the comprehension of low predictability sentences, while slow speech has no effect on contextual facilitation at a moderate level of degradation.

In both the experiments, our results showed a significant main effect of predictability at normal speech rate,
i.e., we observed a facilitatory effect of semantic predictability at normal speech rate under moderate degradation level of 4 channels noise vocoding.
This replicates the findings from earlier studies like @Obleser2010 and @Bhandari2021 in which participants were presented only with normal speech rate, and contextual facilitation was observed at 4 channels noise vocoding.
At this moderate degradation level, listeners were able to decode the context and form its meaning representation.
Consequently, they generated predictions about the upcoming target word in a sentence even in low predictability condition depending on the contextual constrain of the sentences [@Bhandari2021; see also, @Strauss2013].

The expected interaction between speech rate and target word predictability in Experiment 1 showed that comprehension of degraded speech was significantly impaired for low predictability sentences at fast speech rate. In contrast, there was a little to no effect in comprehension of high predictability sentences at fast speech rate under moderate degradation level.
Listening to degraded speech itself requires more attentional resources compared to clean speech [@Wild2012].
When presented as a fast speech, spectral degradation imposes additional cognitive demands; and less time is available to process the auditory signal.
In such a rapidly unfolding event, it is difficult to decode the context information and form its meaning representation from the degraded speech to form predictions about upcoming target word.
This difficulty is heightened when target words are not easily predictable from the context [@Aydelott2004].
As a result, language comprehension in low predictability condition is impaired more than that in high predictability condition.
This detrimental effect on low predictability condition also results in the reduced contextual facilitation in fast speech compared to normal speech observed in Experiment 1.

In contrast to Experiment 1, we did not find the expected interaction between speech rate and target word predictability in Experiment 2,
i.e., decrease in speech rate did not differentially affect the comprehension of high or low predictability sentences although the comprehension tended to decrease at slow speech rate compared to normal speech rate.
As opposed to Experiment 1, we did not observe a significant change in contextual facilitation at slow speech rate at a moderate degradation level in Experiment 2.
Slowing down the speech provides listeners more time to process the information, including the context that is important to generate predictions.
However, our findings show that this ease of processing does not benefit intelligibility and comprehension of sentences with highly predictable target words any more than the sentences with less predictable target words.
This claim is in line with the results of @Winn2021b] who reported that intelligibility does not increase when the speech is slowed down even though there is a difference in the intelligibility between high and low predictability sentences at both normal and slow speech rates.

Accounts from speech perception, and predictive language processing point to a common expectation: contextual facilitation is enhanced when listeners have more time to process the incoming information [CITE].
Additionally, there are conflicting empirical evidence whether increase or decrease of speech rate provides benefit in intelligibility, comprehension, and contextual facilitation.
Given these state of affairs, our findings add new theoretical insights with empirical support into the interplay among spectral degradation, speech rate, and semantic prediction.
Although reducing the speech rate provides time to process the information (including the context) in the degraded speech, this eases the processing of both high and low predictability to a similar extent.
And thus, no increased facilitatory effect is observed at slow speech rate. In contrast, increasing the speech rate adds more cognitive load on the top of the effort required to process degraded speech.
This results in difficulty in processing and understanding the rapidly unfolding sentences among which this difficulty is further increased when the target words are not easily predictable. 

We note a limitation in our study. We tested only with one expansion factor of 1.35, and one compression factor of 0.65.
Although less likely, it can be speculated that when the speech is expanded to a greater degree by including other expansion factors, an increase in facilitatory effect could be observed [cf. ] which was not the case in the current study.


To conclude, we show that processing speed and constrains in attentional and cognitive resources are key factors that influence contextual facilitation of moderately degraded speech.
When enough time is available to process information, i.e., at slow speech, contextual facilitation does neither increase nor decrease.
However, at a time crunch of information processing, i.e., at fast speech, contextual facilitation is reduced such that the fast speech is detrimental to understanding words that are not easily predictable from the context. 


## Conclusions
