---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
bib-humanities: true
documentclass: book
bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

<!-- # Citations, cross-references, and collaboration {#cites-and-refs}  -->
<!-- \chaptermark{Citations and cross-refs} -->

# Discussion and conclusion {#chapter-conclusion}

In this chapter we present a closing remark on *the interaction of top-down predictive and bottom-up auditory processing in comprehension of degraded speech*.
An overview of the summary of the preceding chapters provided, and
it is put in the broader context of probabilistic language processing.
The noisy channel model of communication that was introduced in Chapter \@ref(chapter-introduction) in now presented in relation to the findings of the our studies.
Then we conclude with the implications, limitations, and outlook and considerations for future work.

## Overview of the main findings

The field of language science is dominated by the view that human readers and listeners use context information to form linguistic predictions.
Nonetheless, there are objections to the ubiquitious nature of predictive language processing.
How often do we predict --- only in the lab in an unnatural environment, in a passive listening condition, or also during a conversation?
At what level or linguistic hierarchy --- phonemes, lexicons, semantics, syntax?
Does everyone predict equally well --- illiterates, second language learners, aphasics?
Is prediction limited by other top-down and bottom-up factors --- attention, information processing speed?
In the first chapter, we showed that prediction is not as ubiquitous as it is supposed to be.

When the speech was severely degraded, listeners were not able to utilize context information.
This can, of course, be attributed to the unintelligibility of the highly degraded speech.
However, when the speech was not severely degraded (at 6- and 8-channel noise-vocoding), the facilitatory effect of prediction was not found
when they did not attend to the sentence context.
On the contrary, when the sentence context was attended to, the context facilitated comprehension of the same degraded speech.
It is to say that, attention can limit predictability effect: *no attention, no prediction*, in degraded speech comprehension.
Qualitatively, it also replicated the prior findings that when the bottom-up input is less reliable due to degradation,
listeners rely on lexical-semantic cues.

In the next chapter (Chapter \@ref(chapter-graded-prediction)), we further examined this effect of predictability examining the nature of predictability.
Since we already showed in Chapter \@ref(chapter-attention-prediction) that attention to the context is necessary for predictibility effect,
in this chapter, our instruction did not bind participants' attention to only the target-word.
They could attend to the context, and form a meaning representation of the context.
This chapter revealed that predictability facilitates language comprehension in a graded manner but only when the speech is moderately degraded at 4-channel noise-vocoding.
At the extremes, listeners can either not utilize the context (unintelligibile at 1-channel),
or, the context and target word are clearly intelligibile such that the listeners' identify the target word based on the bottom-up information rather than the context alone.
These findings refute the claim of *narrowed expectations* frameword proposed by @Strauss2013.
Contrary to their claim that predictions are made only for highly predictable sentence endings,
we found that listeners predict target words across a wide range of sentence endings including those in the low and medium predictability sentences.

After we showed in Chapter 6 that predictability effects are observed at the moderate degradation level of 4-channel noise-vocoding,
in Chapter \@ref(chapter-speech-rate), we ask the question if a change in speech rate at 4-channel noise-vocoding, which increases or decreases listening effort and the rate of information flow, further increases or decreases the predictability effect.
We performed this bottom-up manipulation in two experiments: first we compared the contextual facilitation at the moderate degradation level in normal speech and fast speech.
Then we compared the same in normal speech and slow speech rate.
The findings of the experiments presented in this chapter showed, contrary to our expectations, that slow speech does not amplify the contextual facilitation initially observed in normal speech rate.
Listeners already perform at their optimal level in normal speech rate;
slowing down does not necessarily provide any benefit in contextual facilitation than what is there in the normal speech rate.
On the contraty, fast speech impairs the processing of low predictability sentences with no impairment in the comprehension of high predictability sentences.
These findings showed that with a restricted time in the processing of fast speech,
lexical access and activation is impaired.
This is disproportionately affects the comprehension of low predictability sentences, as the activation of less predictable sentence endings are impaired more than those of highly predictable sentence endings in the limited time available for lexical processing.

Despite being certain about the speech quality of subsequent trials in the *predictable channel context*, in Chapter 5,
listeners did not adapt to the degraded speech at all noise-vocoding levels.
This is contrary to most of the extant findings in the literature of speech perception and perceptual learning.
We reason in Chapters 5 and 6 that a constant trial-by-trial variability in higher level feature of speech stimuli (e.g., predictability), impedes listeners' ability to adapt to degraded speech,
regardless of the certainty about next-trail speech quality which has been the misplaced focus in most of the studies in the field.
In Chapters 6 and 7, we also introduced a new approach to calculate response accuracy when listeners response includes context evoking words,
which is to include only those trials in which such words are identified correctly before calculating the accuracy of target word.

Taken together, this thesis' contribution to the field can be stated as:

> When listeners attend to sentence context, semantic predictability facilitates language comprehension at a moderate level of spectral degradation.
Such a contextual facilitation is optimal at a normal speech rate, which is not necessarily amplified by slowing down the speech rate. However, increasng the speech rate reduces the contextual facilitation by restricting the lexical access in the less predictable sentence endings.

## Probabilistic prediction in a noisy channel


## Revisiting the goals

We started this thesis, mentioning some goals.
Here, we revisit those goals and review to what extent we were able to achieve those goals.

### Replication of the predictability effect in a noisy channel

In Chapter \@ref(chapter-attention-prediction), we found that the response accuracy between high and low predictability sentences are significantly different at 8-channel.
In Chapter \@ref(chapter-graded-prediction), the predictability effect was observed also in 4-channel (graded in nature).
These findings are qualitatively similar to @Obleser2007 and @Obleser2010 who also found similar effects at 8-channel and 4-channel noise-vocoding, respectively.
In Chapter \@ref(chapter-speech-rate) again, we found predictability effect at the moderate degradation level of 4-channel noise-vocoding.
<!--However, in Chapter \@ref(chapter-graded-prediction), the results seemed to be different!
Although the accuracy in high and low predictability sentences were significantly different in 8- and 6-channel similar to the preceding chapter,-->
<!-- we also observed the effect of predictability in 4-channel noise-vocoding. -->
<!--Furthermore, it was degraded in nature in 4-channel.-->
Predictability effects are observed at 4-channel as well as 8-channel.
We address these seemingly discrepant findings across the studies later in this chapter.
It suffices to say now, that this thesis replicated prior findings, and also replicated the predictability effect at 4-channel noise-vocoding in more than one experiment reported here.

### Nature of prediction

The debates on the nature of prediction in clean speech perception and reading studies are abundant.
In this thesis, we started with an aim to examine whether the predictability effect is an all-or-nothing phenomenon or if it is graded in nature,
in the case of degraded speech comprehension.
We showed in Chapter \@ref(chapter-graded-prediction) that prediction in degraded speech comprehension is graded in nature and not all-or-nothing;
this is especially true when the speech is moderately degraded at 4-channel noise vocoding.
Only @Strauss2013 have proposed the nature of predictability effect in degraded speech comprehension.
Our findings did not support their claim that the predictability effects are restricted to a narrow rage,
and that listeners make predictions only about highly predictable sentences endings while ignoring the less predictable ones.
All in all, this thesis achieved the goal of examining the nature of prediction in degraded speech comprehension.
It showed that predictions are not restricted only to the most likely sentence endings.

### Boundary conditions of predictive language processing

In Chapter \@ref(chapter-attention-prediction), this thesis examined the effect of attention allocation in predictability effects.
Inspired from a wide variety of literature which shows that listeners can flexibly allocate attention to parts of speech stream,
ant temporal attention can limit predictive processing in non-speech auditory processing,
this thesis examined the role of attention in predictive processing of degraded speech.
By manipulating attention allocation to target word and context in two experiments, this thesis showed that if listeners do not allocate attention to the sentence context, they cannot utilize context information for linguistic predictions.
It is to say that, attention to context was shown to be a limiting factor in linguistic prediction.
Therefore, this goal of examining the boundary conditions of predictive language processing was achieved, precisely in Chapter 6.

### Adaptation to degraded speech

In Chapters \@ref(chapter-attention-prediction) and \@ref(chapter-graded-prediction), trial number was included in the fixed effects structure in the mixed effects modelling of the data.
The results showed no significant effect of trial number.
Response accuracy did not increase over the course of experiment in either of the experiments in multiple conditions:
whether or not listeners paid attention to the context and whether or not listeners were certain about the next-trial speech quality.
The goal was to examine if listeners adapt to the degraded speech (i.e., bottom-up perceptual property) and if it interplays with the top-down semantic property of speech.
We achieved the goal in showing that the listeners indeed do not adapt to the degraded speech which is due to the interference of semantic property of the speech in the retuning of auditory system for perceptual adaptation.

### Speed of information processing

The goal was to test if a change in speech rate has an effect in contextual facilitation of degraded speech comprehension.
The results of Chapter \@ref(chapter-speech-rate) showed that the contextual facilitation is at its optimal when the speech rate is normal.
Slowing down does not increase the facilitation, but speeding up impairs it through low predictability sentences.
When the speed of information processing is fast, the activation of the words that are less predictable in the less constraining sentence constrains is difficult;
the time is restricted for lexical processing.
This difficulty is in addition to the intrinsic nature of effortufl listening of degraded speech.

### Metric for measurement of language comprehension

The inconsistent use of metrics of calculating and measuring language comprehension, given a context, leaves the interpretation of results of existing studies open to ambiguity and inconsistency.
We aimed to establish and consistently use a metric of calculating and measuring language comprehension when the response in a context is under question.
In Chapters \@ref(chapter-graded-prediction) and \@ref(chapter-speech-rate), we argued for not including the trials in analyses in which the particpants wrongly identify the context.
We also performed the data analysis follwing the same procedure of excluding the trials in which context-evoking verbs are identified incorrectly.



